#!/usr/bin/env ruby
# frozen_string_literal: true

# =============================================================================
# provision-org-sites.rb
# =============================================================================
#
# Rolls the GitHub Pages scaffold out to the org repos registered in
# `_data/hub.yml`, so each publishes its own project site at
# https://<org>.github.io/<repo>/ rendered with the zer0-mistakes theme
# (`remote_theme`) — content never leaves the source repo.
#
# Per repo it:
#   1. clones the repo and analyzes its content layout (sections, timeline),
#   2. renders templates/org-site/* (_config.yml + _data/navigation/main.yml),
#   3. opens a pull request with the scaffold (branch: zer0/pages-scaffold) —
#      or pushes directly with --direct,
#   4. with --enable-pages, enables GitHub Pages ("deploy from branch").
#
# Safety:
#   - A repo whose _config.yml was NOT generated by this script is skipped
#     (never clobbers a hand-rolled site config).
#   - Re-running is idempotent: identical scaffold -> no new PR/commit.
#
# Usage:
#   ruby scripts/provision-org-sites.rb --dry-run            # preview everything
#   ruby scripts/provision-org-sites.rb                      # open scaffold PRs
#   ruby scripts/provision-org-sites.rb --enable-pages       # PRs + enable Pages
#   ruby scripts/provision-org-sites.rb --repos 2005 --direct
#   ruby scripts/provision-org-sites.rb --stage /tmp/out     # render files locally only
#   ruby scripts/provision-org-sites.rb --check              # validate registry + templates
#
# Requires `gh` (repo + pages write for the real run) and `git`.
# =============================================================================

require 'optparse'
require 'fileutils'
require 'tmpdir'
require_relative 'lib/hub'

TEMPLATE_DIR    = File.join(Hub::ROOT, 'templates', 'org-site')
CONFIG_TEMPLATE = File.join(TEMPLATE_DIR, '_config.yml.template')
NAV_TEMPLATE    = File.join(TEMPLATE_DIR, 'navigation-main.yml.template')
SCAFFOLD_MARKER = 'zer0-mistakes org hub scaffold'
BRANCH_NAME     = 'zer0/pages-scaffold'

def render(template, vars)
  vars.reduce(File.read(template, encoding: 'utf-8')) do |text, (key, value)|
    text.gsub("{{#{key}}}", value.to_s)
  end
end

def yaml_quote(text)
  text.to_s.gsub('"', '\"')
end

# Nav entries for the repo's root content files and sections, rendered as
# site-relative URLs (the theme's relative_url filter prefixes the baseurl).
def nav_items(clone, files)
  items = +''
  files.reject { |f| f.include?('/') }
       .reject { |f| %w[index readme].include?(File.basename(f, '.md').downcase) }
       .each do |f|
    base = File.basename(f, '.md')
    items << "- title: #{Hub.title_of(File.read(File.join(clone, f), encoding: 'utf-8'), base)}\n" \
             "  icon: bi-clock-history\n" \
             "  url: /#{base}/\n"
  end
  files.select { |f| f.include?('/') }.map { |f| f.split('/').first }.uniq.sort.each do |dir|
    index = File.join(clone, dir, 'index.md')
    title = File.exist?(index) ? Hub.title_of(File.read(index, encoding: 'utf-8'), dir) : Hub.humanize(dir)
    items << "- title: #{title}\n" \
             "  icon: bi-folder\n" \
             "  url: /#{dir}/\n"
  end
  items.chomp
end

def scaffold_files(repo, cfg, clone)
  excludes = (cfg['defaults'] || {})['exclude'] || []
  files    = Hub.content_paths(Dir.chdir(clone) { Dir.glob('**/*.md') }, excludes)

  vars = {
    'ORG'              => cfg['org'],
    'REPO'             => repo['name'],
    'REPO_TITLE'       => yaml_quote(repo['title'] || repo['name']),
    'REPO_DESCRIPTION' => yaml_quote(repo['description']),
    'THEME_REPO'       => cfg.dig('pages', 'theme_repo'),
    'BRANCH'           => repo['branch'],
    'NAV_ITEMS'        => nav_items(clone, files)
  }

  {
    '_config.yml'               => render(CONFIG_TEMPLATE, vars),
    '_data/navigation/main.yml' => render(NAV_TEMPLATE, vars)
  }
end

def write_scaffold(base_dir, rendered)
  changed = []
  rendered.each do |rel, content|
    path = File.join(base_dir, rel)
    next if File.exist?(path) && File.read(path, encoding: 'utf-8') == content

    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, content)
    changed << rel
  end
  changed
end

def open_pr(repo, cfg, clone, changed, direct:)
  org  = cfg['org']
  slug = "#{org}/#{repo['name']}"

  Dir.chdir(clone) do
    if direct
      Hub.run_cmd('git', 'add', *changed)
      Hub.run_cmd('git', 'commit', '-m', 'feat(pages): publish via GitHub Pages with the zer0-mistakes theme')
      Hub.run_cmd('git', 'push', 'origin', repo['branch'])
      Hub.log_info "  pushed scaffold directly to #{slug}@#{repo['branch']}"
      return
    end

    Hub.run_cmd('git', 'checkout', '-B', BRANCH_NAME)
    Hub.run_cmd('git', 'add', *changed)
    Hub.run_cmd('git', 'commit', '-m', 'feat(pages): publish via GitHub Pages with the zer0-mistakes theme')
    Hub.run_cmd('git', 'push', '--force', 'origin', BRANCH_NAME)

    existing = JSON.parse(Hub.run_cmd('gh', 'pr', 'list', '--repo', slug, '--head', BRANCH_NAME,
                                      '--state', 'open', '--json', 'url'))
    if existing.empty?
      body = <<~BODY
        Adds the GitHub Pages scaffold generated by
        [zer0-mistakes/scripts/provision-org-sites.rb](https://github.com/#{cfg.dig('pages', 'theme_repo')}/blob/main/scripts/provision-org-sites.rb):

        - `_config.yml` — publishes this repo at https://#{org}.github.io/#{repo['name']}/ using `remote_theme: #{cfg.dig('pages', 'theme_repo')}`. Content stays plain markdown; the GitHub Pages default plugins render it.
        - `_data/navigation/main.yml` — navbar/sidebar entries for the repo's sections.

        Once merged (with Pages enabled, "deploy from branch"), the site builds automatically on every push.

        🤖 Generated with [Claude Code](https://claude.com/claude-code)
      BODY
      url = Hub.run_cmd('gh', 'pr', 'create', '--repo', slug, '--base', repo['branch'], '--head', BRANCH_NAME,
                        '--title', 'feat(pages): publish via GitHub Pages with the zer0-mistakes theme',
                        '--body', body).strip
      Hub.log_info "  opened PR: #{url}"
    else
      Hub.log_info "  updated existing PR: #{existing.first['url']}"
    end
  end
end

def enable_pages(repo, cfg)
  org = cfg['org']
  out, err, status = Open3.capture3(
    'gh', 'api', '-X', 'POST', "repos/#{org}/#{repo['name']}/pages",
    '-f', "source[branch]=#{repo['branch']}", '-f', 'source[path]=/'
  )
  if status.success?
    Hub.log_info "  Pages enabled: #{JSON.parse(out)['html_url']}"
  elsif err.include?('409') || out.include?('already exists')
    Hub.log_info '  Pages already enabled'
  else
    Hub.log_warn "  could not enable Pages: #{err.lines.first&.strip}"
  end
end

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

options = { mode: :provision, dry_run: false, repos: nil, direct: false, enable_pages: false, stage: nil }
OptionParser.new do |opts|
  opts.banner = 'Usage: ruby scripts/provision-org-sites.rb [options]'
  opts.on('--check',         'validate registry and templates, no network')   { options[:mode] = :check }
  opts.on('--dry-run',       'show planned changes without pushing anything') { options[:dry_run] = true }
  opts.on('--repos LIST',    'comma-separated subset of repos')               { |v| options[:repos] = v.split(',').map(&:strip) }
  opts.on('--direct',        'commit to the default branch instead of a PR')  { options[:direct] = true }
  opts.on('--enable-pages',  'enable GitHub Pages (deploy from branch)')      { options[:enable_pages] = true }
  opts.on('--stage DIR',     'render scaffold files into DIR/<repo>/ only')   { |v| options[:stage] = v }
end.parse!

cfg    = Hub.load_registry
errors = Hub.validate_registry(cfg)
[CONFIG_TEMPLATE, NAV_TEMPLATE].each do |t|
  errors << "missing template: #{t.sub("#{Hub::ROOT}/", '')}" unless File.exist?(t)
end

unless errors.empty?
  errors.each { |e| Hub.log_error(e) }
  exit 1
end

if options[:mode] == :check
  Hub.log_info 'hub registry and org-site templates are valid'
  exit 0
end

repos = Hub.discover_repos(cfg)
repos.select! { |r| options[:repos].include?(r['name']) } if options[:repos]
if repos.empty?
  Hub.log_warn 'no repos to provision (check org, exclude_repos, or --repos filter)'
  exit 0
end

Hub.log_info "Provisioning #{repos.size} repo(s) in #{cfg['org']}: #{repos.map { |r| r['name'] }.join(', ')}"

Dir.mktmpdir('hub-provision') do |tmp|
  repos.each do |repo|
    slug  = "#{cfg['org']}/#{repo['name']}"
    clone = File.join(tmp, repo['name'])
    Hub.log_info "#{slug}:"
    Hub.run_cmd('git', 'clone', '--quiet', '--branch', repo['branch'],
                "https://github.com/#{slug}.git", clone)

    existing_config = File.join(clone, '_config.yml')
    if File.exist?(existing_config) && !File.read(existing_config, encoding: 'utf-8').include?(SCAFFOLD_MARKER)
      Hub.log_warn '  has a hand-rolled _config.yml — skipping (manage it in the repo itself)'
      next
    end

    rendered = scaffold_files(repo, cfg, clone)

    if options[:stage]
      stage_dir = File.join(options[:stage], repo['name'])
      write_scaffold(stage_dir, rendered)
      Hub.log_info "  staged scaffold in #{stage_dir}"
      next
    end

    changed = options[:dry_run] ? rendered.keys.reject { |rel| File.exist?(File.join(clone, rel)) && File.read(File.join(clone, rel), encoding: 'utf-8') == rendered[rel] } : write_scaffold(clone, rendered)

    if changed.empty?
      Hub.log_info '  scaffold already up to date'
    elsif options[:dry_run]
      Hub.log_info "  DRY: would update #{changed.join(', ')} and open a PR"
    else
      open_pr(repo, cfg, clone, changed, direct: options[:direct])
    end

    if options[:enable_pages]
      if options[:dry_run]
        Hub.log_info '  DRY: would enable GitHub Pages (deploy from branch)'
      else
        enable_pages(repo, cfg)
      end
    end
  end
end

Hub.log_info 'Provisioning complete'
